from PySide6.QtCore import Qt, QAbstractListModel, Slot, QModelIndex, QObject, QUrl
from PySide6.QtQml import QmlElement
from ..modules.logger import get_instance
from .prjsetmodelitem import PrjSetModelItem
from .historymodel import HistoryModel
import yaml

QML_IMPORT_NAME = "PrjSetModel"
QML_IMPORT_MAJOR_VERSION = 1

logger = get_instance(__name__)


@QmlElement
class PrjSetModel(QAbstractListModel):

    def __init__(self, parent=None):
        super().__init__(parent)
        self._items = []

    def rowCount(self, parent=QModelIndex()):
        return len(self._items)

    def data(self, index, role=Qt.DisplayRole):
        if not (0 <= index.row() < len(self._items)):
            return
        row = self._items[index.row()]
        if role == Qt.DisplayRole:
            return row.name
        elif role == Qt.UserRole + 1:
            return row.value
        elif role == Qt.UserRole + 2:
            return row.desc

    def roleNames(self):
        roles = super().roleNames()
        roles.update({
            Qt.DisplayRole: b"name",
            Qt.UserRole + 1: b"value",
            Qt.UserRole + 2: b"desc"
        })
        return roles

    @property
    def itemsData(self):
        return [(item.name, item.value, item.desc) for item in self._items]

    @Slot(int, int, result=bool)
    def move(self, source: int, target: int):
        """Slot to move a single row from source to target"""
        return self.moveRow(QModelIndex(), source, QModelIndex(), target)

    def moveRow(self, sourceParent, sourceRow, dstParent, dstChild):
        """Move a single row"""
        return self.moveRows(sourceParent, sourceRow, 0, dstParent, dstChild)

    def moveRows(self, sourceParent, sourceRow, count, dstParent, dstChild):
        """Move n rows (n=1+ count)  from sourceRow to dstChild"""
        if (sourceRow < 0 or sourceRow >= len(self._items) or
                dstChild < 0 or dstChild > len(self._items) or
                sourceRow == dstChild):
            return False

        if sourceRow < dstChild:
            dest = dstChild - 1
        else:
            dest = dstChild

        self.beginMoveRows(sourceParent, sourceRow, sourceRow, dstParent, dest + 1 if sourceRow < dstChild else dest)
        item = self._items.pop(sourceRow)
        self._items.insert(dstChild, item)
        self.endMoveRows()
        return True

    @Slot(int, result=QObject)
    def get(self, index):
        if 0 <= index < len(self._items):
            return self._items[index]
        else:
            return None

    def flags(self) -> Qt.ItemFlag:
        flag = super().flags()
        flag |= Qt.ItemIsDragEnabled | Qt.ItemIsDropEnabled
        return flag

    @Slot(str, str, str)
    def addItem(self, name, value, desc):
        logger.info("Added item: %s - %s - %s", name, value, desc)
        self.beginInsertRows(QModelIndex(), len(self._items), len(self._items))
        item = PrjSetModelItem(name, value, desc, self)
        self._items.append(item)
        self.endInsertRows()

    @Slot(int, str, str, str)
    def edit(self, index, name, value, desc):
        logger.info("Edited item at index %s: %s - %s - %s", index, name, value, desc)
        if 0 <= index < len(self._items):
            item = self._items[index]
            item._name = name
            item._value = value
            item._desc = desc
            self.dataChanged.emit(self.index(index, 0), self.index(index, 0))
        else:
            logger.error("Attempt to edit item at invalid index %s", index)

    @Slot(int)
    def removeItem(self, index):
        if 0 <= index < len(self._items):
            self.beginRemoveRows(QModelIndex(), index, index)
            logger.info("Deleted item at index %s", index)
            del self._items[index]
            self.endRemoveRows()

    @Slot()
    def clear(self):
        self.beginResetModel()
        self._items = []
        self.endResetModel()

    @Slot(QUrl)
    def exportYAML(self, file: QUrl):
        file_name = file.toLocalFile()
        logger.info("Exported file: %s", file_name)
        yaml_data = {
            'title': 'Project Settings',
            'desc': "Project Setting includes the static information which is not be changed during runtime. "
            "This parameter should be set during the project development phase and fixed after project deployment. "
            "A file prjset.h shall be generated by script.",
            'data': []
        }
        items_data = self.itemsData
        for item_data in items_data:
            pName, pVal, pDesc = item_data
            yaml_item = {
                'name': pName,
                'value': pVal,
                'desc': pDesc if pDesc != "" else None
            }
            yaml_data['data'].append(yaml_item)
        with open(file_name, 'w') as file:
            yaml.dump(yaml_data, file, sort_keys=False)

    @Slot(QUrl)
    def importYAML(self, file: QUrl):
        file = file.toLocalFile()
        logger.info("Imported file: %s", file)
        try:
            with open(file, 'r') as yaml_file:
                yaml_data = yaml.load(yaml_file, Loader=yaml.FullLoader)
                if isinstance(yaml_data['data'], list):
                    for item in yaml_data['data']:
                        pName = item['name']
                        pVal = item['value']
                        pDesc = item['desc'] if item['desc'] != None else ""
                        self.addItem(pName, pVal, pDesc)
                else:
                    logger.warning("Invalid YAML format in %s. Expected a list.", file)
        except FileNotFoundError:
            logger.error("File not found: %s", file)
        except yaml.YAMLError as e:
            logger.error("Error loading YAML from %s: %s", file, e)
