name: SenseTool CI/CD

on:
  push:
    branches: ["develop"]
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.7.0"
          host: "windows"
          target: "desktop"
          arch: "win64_mingw"
          modules: "qt3d qtcharts qtconnectivity qtdatavis3d qtgraphs qtgrpc qthttpserver qtimageformats qtlanguageserver qtlocation qtlottie qtmultimedia qtnetworkauth qtpdf qtpositioning qtquick3dphysics qtquickeffectmaker qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtspeech qtvirtualkeyboard qtwebchannel qtwebsockets qtwebview debug_info qt5compat qtquick3d qtquicktimeline qtshadertools"
          dir: "${{ github.workspace }}/Qt/"
          install-deps: "true"

      - name: Add qmltestrunner to path
        run: |
          echo ${{ github.workspace }}/Qt/6.7.0/win64_mingw/bin >> ${{ github.path }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install invoke
          pip install -r requirements.txt

      - name: Invoke Test
        run: |
          invoke test

      - name: Deploy App
        run: |
          invoke deploy

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
